#!/bin/bash

check=$(pip list --outdated --format=freeze --user)

if [[ $? != 0 ]]; then
   pip list --outdated --format=freeze --user | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install --upgrade --user
fi
